agency: SF

client:
  base_url: http://api.511.org/
  params:
    api_key: <REDACTED>

serial:
  port: /dev/ttyACM0
  baudrate: 9600

init:
  - template: |
      SFTrainSign
      for SF MUNI
    duration: 3
  - template: <3, James T
    duration: 2

loop:
  - template: |
      {{ now("America/Los_Angeles", format="%H:%M") }}
      sfmta.com
    duration: 5
